### PR TITLE
Update dependency cytoscape@3.3.2

### PR DESCRIPTION
**Pull request by Spaxe**
Made the minimum change to have Cytoscape@3.3.2 in the dependency chain.

### CODE REVIEW

**Comment by maxkfranz** [comment]
Thanks for the PR, I'll update to v3.3 once a few more patch releases have been made to make sure there's consistent stability for this project.

For now, it should be possible with the semver range in package.json to manually `npm i cytoscape@3.3` to use v3.3.x in your project.

**Comment by vivekvs1** [comment]
I would like to request for updating to the new Cytoscape version which has support for 'taxi' edges 💃

**Comment by vetertann** [comment]
Hello, I would also like to request this feature (and dagre layout control points, if ot is possible:)

**Comment by maxkfranz** [comment]
This dependency shouldn't be updated directly.  It should specify the minimum known version that works -- not the latest.

See https://github.com/plotly/react-cytoscapejs/issues/21#issuecomment-496322993

**Comment by MichBri** [comment]
I also would like to request this feature. I would be fine to have the taxi-curve-style available.

**Pull request closed without merging**
