### PR TITLE
use React refs

### LINKED ISSUE #48: FindDomNode deprecation warning with StrictMode
I'm using this package in a newly created Reactjs project with create-react-app, which creates the project using React.StrictMode. Because of this I have the following warning:

`Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of t which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node`

It should be updated as the Reactjs docs recommend, I don't think it would be better to remove the StrictMode just for a single component.

### PR DESCRIPTION
**Pull request by sgratzl**
closes #48

### CODE REVIEW

**Comment by 70nyIT** [comment]
Love that to be merged!

**Comment by markdesign** [comment]
Please Merge, thank you!

**Comment by akx** [comment]
@maxkfranz Review please?

**Comment by maxkfranz** [comment]
I believe the folks at Plotly are maintaining this in tandem with the Dash component.  I think it may be @xhlulu who's responsible for the Dash component, or @alexcjohnson may be able to refer someone at Plotly to review.

**Comment by yaxue1123** [comment]
Please merge! Many thanks!

**Pull request merged**
